name: Build C++

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
    contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install build-essential
        sudo apt-get install cmake
        sudo apt-get install libyaml-cpp-dev
        sudo apt-get install libspdlog-dev
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt install python3.10 python3.10-dev python3.10-distutils python3-pip
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1
        python3.10 -m pip install pybind11

    - name: Build C++
      run: |
        cd src_cpp
        source setup_env.sh