name: Documentation

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme

    - name: Generate Sphinx Documentation
      run: |
        # Assuming your docs configuration is in the 'docs' directory
        sphinx-apidoc -o docs/source/ .
        sphinx-build -b html docs/source/ docs/build/html

    - name: Install LaTeX packages
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

    - name: Build PDF documentation with LaTeX
      run: |
        sphinx-build -b latex docs/source/ docs/build/latex
        cd docs/build/latex
        make all-pdf

    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: documentation-artifacts
        path: |
          docs/build/html
          docs/build/latex/*.pdf
