name: Documentation

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:
permissions:
  contents: write
      
jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme
        pip install piccolo_theme
        pip install sphinx-autoapi
        pip install sphinx_book_theme

    - name: Generate Sphinx Documentation
      run: |        
        sphinx-build -b html docs/ docs/_build/html

    - name: Upload Documentation Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation-artifacts
        path: |
          docs/_build/html          
          
