name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc3
          pip install -r requirements_updated.txt

      - name: Generate documentation
        run: |
          # Generate docs for all modules under src
          pdoc --html --skip-errors --output-dir docs src

      - name: Install wkhtmltopdf for PDF conversion
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Convert HTML to PDF
        run: |
          # Assuming docs are in docs directory, convert each HTML file to PDF
          find docs -name "*.html" -type f -exec sh -c 'wkhtmltopdf "$1" "${1%.html}.pdf"' _ {} \;

      - name: Merge PDFs
        run: |
          # Merge all PDFs into a single file
          gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=merged_docs.pdf $(find docs -name "*.pdf")

        - name: Commit and Push PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.pdf
          git add *.html
          git commit -m "Update project documentation"
          git -c http.extraHeader="AUTHORIZATION: basic $(echo -n x-access-token:${GITHUB_TOKEN} | base64)" push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}