name: Run Unit Tests

on:
  push:
    branches:
      - main  # Replace 'main' with the default branch name of your repository if it's different
  pull_request:
    branches:
      - main  # Replace 'main' with the default branch name of your repository if it's different

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cpu

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AUTH_SECRET_KEY: ${{ secrets.AUTH_SECRET_KEY }}
      run: pytest tests
